### ISSUE TITLE
unable to add icloud caldav to ha

### ISSUE THREAD

**Issue by balajeek** [python-caldav/caldav#172]
I subscribed to a public calendar and added to my apple icloud, i am able to see the calendar and events on icloud.

next, i added the following in config.yaml on my latest HA, found the caldav url with the help of this instructions found at this site https://ict4g.net/adolfo/notes/admin/determining-url-of-caldav-calendars.html

```
calendar:
  - platform: caldav
    url: "https://p41-caldav.icloud.com/93866047/calendars/96E8CA14-9A06-4430-B780-9F4F65BABFF7"
    username: !secret icloud_un
    password: !secret icloud_pw
    calendars:
      - Recycle
```

After HA restart, i do not see the calendar in calendar section, upon looking at the log i see this error:

`
2022-02-28 11:36:09 ERROR (SyncWorker_6) [caldav] Deviation from expectations found.  Please raise an issue at https://github.com/python-caldav/caldav/issues or reach out to t-caldav@tobixen.no, include this error and the traceback and tell what server you are using
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/caldav/lib/error.py", line 25, in assert_
    assert(condition)
AssertionError
2022-02-28 11:36:09 ERROR (MainThread) [homeassistant.components.calendar] Error while setting up caldav platform for calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/caldav/calendar.py", line 87, in setup_platform
    calendars = client.principal().calendars()
  File "/usr/local/lib/python3.9/site-packages/caldav/objects.py", line 474, in calendars
    return self.calendar_home_set.calendars()
  File "/usr/local/lib/python3.9/site-packages/caldav/objects.py", line 441, in calendar_home_set
    if '@' in calendar_home_set_url and not '://' in calendar_home_set_url:
TypeError: argument of type 'NoneType' is not iterable
`
